### ISSUE TITLE
Make a `dist` of dGrid without AMD, without dependencies.

### ISSUE THREAD

**Issue by gaurav21r** [SitePen/dgrid#1171] opened 2015-08-20 08:30 UTC
Like most other projects I think it would be super useful to have a `dist` folder and maybe a **Dojo Build** to create a single `.js` lyer file with **Zero Dependencies** on Dojo / dStore / any AMD Loader. This can be part of the `Gruntfile.js`.

The specific use case I'm running into is that I'm packaging dGrid into a webcomponent and then `require`ing it somewhere. While testing using **The Intern** \* theintern/intern, the AMD loaders are clashing. 

But I feel this is required generally too, where dGrid needs to be used in a non AMD environment. People who use it in Dojo projects can continue `requiring` dGrid.

**Comment by dylans** [comment] 2015-08-20 11:51
This part doesn't make sense to me: "While testing using The Intern * theintern/intern, the AMD loaders are clashing." That's what the loaders and loaderOptions configuration settings are for: https://theintern.github.io/intern/#common-config

I don't know why you would think that AMD cannot be used with web components however? Every environment can be made into an AMD environment. delite and deliteful are a web components library that use AMD for everything, https://github.com/ibm-js/delite/

Finally, the point on having no dependencies on anything else, do you propose to re-create those dependencies into a single file for dgrid? And are you suggesting that every possible feature for dgrid be included as a single file. And then are you suggesting that it makes sense to expose this all as a global to support non-AMD environments?

You would essentially need to reimplement the following:
* dojo/_base/declare
* dojo/text
* dojo/_base/array (not needed for web components environments, but you'd still need to provide a stub to native code)
* dojo/dom-geometry (not needed for web components environments, but you'd still need to provide a stub to native code)
* dojo/_base/lang
* dojo/string
* dojo/i18n
* dojo/on
* dojo/query
* dojo/aspect
* dojo/has
* dojo/dom-class
* dojo/dom-construct
* dojo/when
* dojo/mouse
* dojo/_base/sniff
* dojo/dom
* dojo/_base/html
* dojo/Deferred
* dojo/json (not needed for web components environments, but you'd still need to provide a stub to native code)
* dijit/registry
* various Dijits if you want those editors available

And then whatever dependencies dstore has (e.g. dojo/request, dojo/promise, etc.). The point is, the list of dependencies isn't small. Even though dgrid can be optimized into a build that's very small, if you try to include all of the features, that increases the dependencies.

One of our plans is to create a refactored version of dgrid that relies on Dojo 2's capabilities, using TypeScript, which would then let you export the code to UMD or even non-wrapped JavaScript, if authored using TypeScript, but that's at least a few months away if not more.

**Comment by gaurav21r** [comment] 2015-08-20 18:23
Hi @dylans Thanks for your detailed reply! I'm writing my thoughts with subheadings so as to keep the discussion organised!

**My Problem with Intern**
I'm sorry i am new to intern and I may be mistaken but I thout the `loaderOptions` was to **replace** intern's exisiting loader, not add a new one. Even if one were to do that, there is no option (that I could see on a preliminary look) in the dojo loader of **namespaced** loading like we have in requirejs: http://requirejs.org/docs/faq-advanced.html#rename. Without namespaces, how would intern know that a certian `require` is from the Dojo Loader within my webcomponent and another `require` is Intern's own AMD loader (which is the `dojo.js` inside its `node_modules` I think!) ?

**The case for a built version**
In any case, I meant having a built distribution in a general sense, not particular to my problem. Theoretically, this proposal does not differ from **built versions** of dojo.

**HTML Imports vs AMD**
Yes, **delite** are doing webcomponents their way, but a huge majority of Web Component developers out there are using **Polymer** and **HTML Imports**. http://component.kitchen/components

**Using AMD with WebComponents**
AMD and even CommonJS doesn't find an audience for webcomponent authors. I had a look at this discussion but could not see anything fruitful -> https://groups.google.com/forum/#!topic/polymer-dev/bdSyt-QXFE8

**What I propose for `dist/`**
> Finally, the point on having no dependencies on anything else, do you propose to re-create those dependencies into a single file for dgrid? And are you suggesting that every possible feature for dgrid be included as a single file. And then are you suggesting that it makes sense to expose this all as a global to support non-AMD environments?

Yes! I'm not saying we re implement the features given by Dojo obviously, I just mean we have a built version in a single file that exposes dGrid as a global. So I can do something like:

```js
<script src="angular.min.js"> </script>
<script src="jquery.js"> </script>
<script src="dgrid.js"> </script>
<script>
  //No Dojo No AMD No requires are explicitly needed!
  var myGrid = new dGrid({});
</script>
```

**Cost to implement this**
The cost to implement the above is minimal. And non invasive changes to the repo. All one needs is 

1. A `dgrid.profile.js` to be run with Dojo's build tools.
2. A grunt task to automate the above.
3. A `dist` folder to store the output from above.

Although a majority of users will still use dGrid within AMD by `requiring` it. I don't think this addition will be a deterrent to anyone. Those worried about the dependency size will most likely be using dojo and requiring dGrid as usual.

**The Other Grids out there**
As a thought, if we consider the other grids out there from dGrid's own comparison page ie.: **SlickGrid** **ng-grid** **GridX** **jqGrid** et al. Though some of them do need an AMD loader, a majority are drop in grids (when their framework has been loaded). I haven't looked at this list much but I have experience of using grids extensively from the early days of **dGrid** to **HandsOnTable**, **hyperGrid** etc.

Finally, 
> One of our plans is to create a refactored version of dgrid that relies on Dojo 2's capabilities, using TypeScript, which would then let you export the code to UMD or even non-wrapped JavaScript, if authored using TypeScript, but that's at least a few months away if not more.

That sounds really cool! :+1: Can't wait! Anyplace I can find a roadmap?

**Comment by dylans** [comment] 2015-08-20 19:26
Replies:

> **My Problem with Intern**

Ok, I guess I don't understand what is clashing then. The point was, if you want to use the same loader, then do so. Otherwise, you have a page you run tests on, that page has its own loader and code, and then the tests from Intern load that page and interact with it, but all of its code runs within the context of Intern's loader.

> **The case for a built version**

But a build version is what the build system is for... I'm confused on this point.

> **HTML Imports vs AMD**

Chrome supports HTML imports, Firefox has no plans to because they are a bad idea. http://caniuse.com/#feat=imports

> **Using AMD with WebComponents**

That's because the same people think ES6 modules are perfect, even with their deficiencies and the lack of a completed loader spec. It's not my fault that people suddenly think architecture doesn't matter.

> **What I propose for `dist/`**
> Yes! I'm not saying we re implement the features given by Dojo obviously, I just mean we have a built version in a single file that exposes dGrid as a global. So I can do something like:

This is exactly the type of architecture that AMD and Dojo try to discourage, to encourage you to do things the right way, rather than a hacked together way. I would far prefer to support something that uses ES6 modules than 3 script tags and a global object.

> **Cost to implement this**
> The cost to implement the above is minimal. And non invasive changes to the repo. All one needs is 

> 1. A `dgrid.profile.js` to be run with Dojo's build tools.
> 2. A grunt task to automate the above.
> 3. A `dist` folder to store the output from above.

I don't think it's anywhere near as easy as this, but prove us wrong. Create a pull request with this working and we'll take a look.

> **The Other Grids out there**
> As a thought, if we consider the other grids out there from dGrid's own comparison page ie.: 
> **SlickGrid** **ng-grid** **GridX** **jqGrid** et al. Though some of them do need an AMD loader, a > majority are drop in grids (when their framework has been loaded). I haven't looked at this list much > but I have experience of using grids extensively from the early days of **dGrid** to 
> **HandsOnTable**, **hyperGrid** etc.

Each of them work in the context of their dependencies. Dojo strongly encourages people to do things in a way that performs well.

> Finally, 
> > One of our plans is to create a refactored version of dgrid that relies on Dojo 2's capabilities, using TypeScript, which would then let you export the code to UMD or even non-wrapped JavaScript, if authored using TypeScript, but that's at least a few months away if not more.

> That sounds really cool! :+1: Can't wait! Anyplace I can find a roadmap?

Other than what's on the Dojo roadmap on the website, not yet.

**Comment by gaurav21r** [comment] 2015-08-21 06:45
Thanks @dylans for your feedback. I'd like to do a PR for the same, but it would be good if i could get some help from the core team. Just a few Q's about the Dojo Loader and opinions on the packaging and API of the built code.

> But a build version is what the build system is for... I'm confused on this point.

I'm just suggesting, we include the build process in the `Gruntfile.js` and keep the built version too under version control (a `dist` folder).



> This is exactly the type of architecture that AMD and Dojo try to discourage, to encourage you to do things the right way, rather than a hacked together way. I would far prefer to support something that uses ES6 modules than 3 script tags and a global object.

While I agree with you here, the community at large doesn't. Also, AMD may not be the only dependency manager used out there. **Browserify** which encourages Node.js style commonJS is far more popular, and its architecturally solid as well! I'm not saying replace AMD, it has its merits! I'm just saying give **an option** for no AMD. There would, of course be ONE script tag, I just used it for illustrating how it could play well with other frameworks.

> I don't think it's anywhere near as easy as this, but prove us wrong. Create a pull request with this working and we'll take a look.

Off the top of your head, any *gotchas*? It would be really helpful if I went into this prepared rather than wasting everyone's time!

My approach is going to be to build a `dgrid.profile.js` with a `customBase` and `boot` set to true. Then run the dojo builder to build the entire project inside ONE layer file which would be `dist\dgrid.uncompressed.js` and `dist\dgrid.min.js`. 

I'm thinking about how to pass in the `mixins` like `OnDemandGrid`, `Selection` etc to `declare` in the built file. if everything works, I'll add a Grunt task to `Gruntfile.js` which will basically call the dojo builder and do some cleanup of the built files (since the builder will output the entire `/dojo`, `/dgrid`, `/dstore`, `/put-selector`, `/x-style` source trees!)

**Comment by kitsonk** [comment] 2015-08-21 07:59
> I'm just suggesting, we include the build process in the Gruntfile.js and keep the built version too under version control (a dist folder).

That would presuppose there is a "one size fits all" build.  That is the challenge with JavaScript, there is no one size fits all, ergo, the source distribution.  Would you support all browsers? Would you use advanced optimisations in the closure compiler for this build?  What parts of dgrid would you concatenate into a file?  You will have to make a lot of decisions that a lot of other people are not happy with.

> Browserify which encourages Node.js style commonJS is far more popular,

Define popular.  "Some devs like it" isn't popular in my opinion.  SystemJS is sort of "popular" now and solves the same problem space.  Ultimately, we are all going to align to ES6 modules now though, and while it handles the circular references, there are still some challenges with ES6, but at least it is an agreed standard.

> Off the top of your head, any *gotchas*?

I think what we are trying to kindly state is there are a lot of *gotchas*.  I don't think we are being resistant to it just because... Most of us have lived in a situation where we have had to inherit upstream decisions which put constraints on.  It is like talking to an Expert in the context of the [Dreyfus Model of Skill Acquisition](https://en.wikipedia.org/wiki/Dreyfus_model_of_skill_acquisition), *it depends*.

I personally think a tutorial on a rational dgrid build profile that work in your target environment that outputs a single layer file, containing the features you want as an example would be a better contribution, in my opinion.

**Comment by kitsonk** [comment] 2015-08-21 08:10
Also on the "popularity" contest... [Google](https://www.google.com/trends/explore#q=Browserify%2C%20SystemJS%2C%20RequireJS&cmpt=q&tz=Etc%2FGMT-1) indicates that RequireJS is significantly more popular than Browserify:

<img width="857" alt="google_trends_-_web_search_interest__browserify__systemjs__requirejs_-_worldwide__2004_-_present" src="https://cloud.githubusercontent.com/assets/1282577/9404082/5a93a05e-47e4-11e5-9793-711e0320e360.png">

**Comment by gaurav21r** [comment] 2015-08-27 08:47
@kitsonk  @dylans Your feedback is appreciated, but I don't understand why there is so much resistance to an **optional** feature.

Infact, what I am trying to say has already been outlined in a SitePen tutorial! https://www.sitepen.com/blog/2012/06/11/dgrid-and-dojo-nano-build/

@kitsonk Well, i wasn't considering Google Trends for this as I've been told its an unreliable metric. 

http://stackoverflow.com/questions/2450696/what-happened-to-dojo-in-2008
http://dojo-toolkit.33424.n3.nabble.com/jQuery-and-the-long-term-viability-of-Dojo-td3952249.html

As we all know Dojo is an absolutely fantastic, pioneering framework! But Google trends doesn't give it justice. But yeah, you're right, these things should be empirical. I just go to any IRC and discussion forum or some large frameworks that use JS *isomorphically* and they seem to use CommonJS / Browserify *these days*, that's why I said popular.

I'm almost done with my initial research and PR except for a small glitch here: http://dojo-toolkit.33424.n3.nabble.com/Namespaced-require-amp-define-like-RequireJS-td4006361.html

I'll then be able to send a PR and you guys evaluate / suggest / reject / improve! Cheers!

**Comment by kitsonk** [comment] 2015-08-27 10:06
> Your feedback is appreciated, but I don't understand why there is so much resistance to an optional feature.

Well, it isn't an optional feature if it is checked into the repository.  It becomes a feature that needs to be maintained.  It is also a feature that fits one use case, one use case we would consider rather narrow.  It isn't as much resistance as trying to understand why the desire to add a feature that has such a narrow use case.

I think we would all be fore making something easier to distribute, utilise and consume, but I think we are feeling you are missing some of reason why things are currently distributed the way they are, because one size seldom fits anyone...

Regarding Browserify, generally the approach of the *cult* of the full-stack developer is to take large chunks of code that was designed to run on the server and bang it into a browser...  Ergo, Browserify and CommonJS client side.  I won't go into the debate of why that particular design methodology might make it easy for the developer, but at the sacrifice of the client experience.  Isomorphic JavaScript needs a lot more careful thought than just banging Node modules into Browserify.

Don't take our thoughts as unappreciative either...  Your interest is very much appreciated.

**Closed** 2020-05-14 16:35 UTC
Labels: enhancement, needs-opinions
