### ISSUE TITLE
dgrid sort gets invoked on right click in IE

### ISSUE THREAD

**Issue by swapnilghan** [SitePen/dgrid#1019] opened 2014-10-13 19:35 UTC
I am using dgrid and have written a custom sort function. I also have context menu defined for grid's columns. everything works as expected and life is good in all browsers except IE. In IE grid is sorted for left click as well as right click (I am using IE11). 

is there any way to avoid this? event object doesn't provide details about the click. 

grid.on("dgrid-sort", lang.hitch(this, function(event){
   	}));

**Comment by kfranqueiro** [comment] 2015-10-02 15:56
We still haven't been able to reproduce this issue based on the provided code.  dgrid's event handler for header cells to sort only triggers on the `click` event, which should only respond to left-click.

Given that we can't reproduce this based on any reduced test cases so far, we're closing this issue.  If you can provide a complete test case that we can run that reproduces the issue, we'll take another look.  Thanks!

**Closed by kfranqueiro** 2015-10-02 15:56 UTC
