### ISSUE TITLE
[Bug] Scroll bar jumps on Store Notify

### ISSUE THREAD

**Issue by wildcatcs** [SitePen/dgrid#341] opened 2012-11-14 19:32 UTC
If the OnDemandGrid is scrolled to the bottom of the list of items in the grid when any item in the list is updated via a store notify the scroll bar moves up one position such that the last item is the list is no longer visible.

Looks like the code in List.js is removing the item from the list which causes the list to "scroll up" than re-adds the item back into the list without taking into account the previous position of the scroll bar.

**Comment by kfranqueiro** [comment] 2016-03-28 12:17
#1148 reports this same issue, but also has an example reproduction case, so I'm electing to keep that open and close this.

The issue related to JsonRest always fetching the last item from the server over and over sounds like a different issue typically caused by the server incorrectly (or not at all) reporting the total number of items (e.g. #691).

**Closed by kfranqueiro** 2016-03-28 12:17 UTC
Labels: bug
