### ISSUE TITLE
dgrid content is not placed correctly when header row height is resized.

### ISSUE THREAD

**Issue by PaMcZee** [SitePen/dgrid#1173] opened 2015-08-21 21:30 UTC
I am having an issue with dgrid's content rows not being placed correctly.  The issue occurs when the grid is resized (made smaller), and the text for one or more of the header cells wraps so that the header row's height increases.   The content data is pushed up into the header area, obscuring the bottom portion of the header row text.

I searched the various issues related to this and found an issue where the content is pushed into the header when the grid is first displayed (https://github.com/SitePen/dgrid/issues/249).  However my case is slightly different where  the grid and content start out looking correct, and the act of resizing the grid causes the issue to occur.  It's as if dgrid is not computing the new "top" of the contents correctly when the grid is resized down (thus making the header row "taller").

Looking for a solution, or a confirmation that this is a bug/issue.  I have tried everything at this point to get this to work, and maybe I am doing something wrong.

**Comment by shahzad31** [comment] 2015-08-21 21:48
this issue is most probably a duplicate of https://github.com/SitePen/dgrid/issues/1170

**Comment by shahzad31** [comment] 2015-08-21 21:49
I think this is most probably a duplicate of this issue too
https://github.com/SitePen/dgrid/issues/1170
there is a hack to resolve this , but it isn't dgrid bug
try this
grid.on('dgrid-refresh-complete',function(){
grid.resize();
})

**Comment by kfranqueiro** [comment] 2015-08-21 22:40
As the OP points out, it doesn't sound like a duplicate of that, since in this case, the initial rendering is correct.  (On the other hand, it sounds like #1170 duplicates #249.)

It sounds like in one way or another, dgrid's typical resize handling is not being triggered.  We'd really need to see a reproducible test case to be able to determine the cause, but it's most likely a mistake related to mixins or initialization.

**Comment by PaMcZee** [comment] 2015-08-22 00:34
After doing some digging, it seems that the grid uses a CSS with the .dgrid-scroller set with the margin-top as 25px.  For example:

.dgrid-scroller {
  margin-top: 25px !important;
}

After this setting is another custom grid setting for dgrid-scroller.

#myGrid .dgrid-scroller {
    ... stuff for myGrid 
}

The previous margin-top entry is causing the issue of the content data flowing into the header of myGrid.  So I thought I had this solved, but there does not seem to be a way to set the margin-top in myGrid, i.e. make dgrid treat the margin-top setting as if it were not specified previously.

I tried various margin-top settings in myGrid (0, auto, etc.), and none worked.  So basically, I would like to "turn off" the margin-top setting in myGrid, but not been able to find the correct setting / entry to do so.

**Comment by kfranqueiro** [comment] 2015-08-22 01:12
dgrid should already be overriding this style inline as part of its [`resize` method](https://github.com/SitePen/dgrid/blob/v0.4.0/List.js#L284), and your problem seems to indicate that is never running, which is why I asked for a test case.

Are you sure your grid instance has been started up?  dgrid typically [only fires its resize logic once that is called](https://github.com/SitePen/dgrid/blob/v0.4.0/List.js#L94-L96).

dgrid calls `startup` automatically if the grid is in document flow at the time it's created, but otherwise you need to call it once you place it.

**Comment by kfranqueiro** [comment] 2016-02-03 18:45
Given no further response or test case, and the likelihood that this boils down to improper startup, I'm closing this issue. If you still encounter it, please provide a test case so we can debug further. Thanks!

**Closed by kfranqueiro** 2016-02-03 18:45 UTC
Labels: needs-info
