### ISSUE TITLE
Custom Build and extension locales

### ISSUE THREAD

**Issue by fredfortier** [SitePen/dgrid#1136] opened 2015-06-04 00:41 UTC
I am including dgrid in a custom layer. Somehow, "dgrid/extensions/nls/pagination.js" is left out. I can't seem to find an "switch" to tell it to include in in the build. My other nls seem to come in fine. Any ideas?

**Comment by kfranqueiro** [comment] 2015-06-04 02:16
Can you provide your build profile so we can try to reproduce the issue?

**Comment by fredfortier** [comment] 2015-06-04 02:26
var profile = {
    basePath: "src/main/webapp",
    releaseDir: "../../../target",
    action: "release",
    optimize: false,
    layerOptimize: false,
    stripConsole: "warn",
    packages: ["xstyle", "put-selector", "dgrid", "dstore", "myapp"],
    plugins: {
        "xstyle/css": "xstyle/build/amd-css"
    },
    layers: {
        "myapp/myapp": {
            include: ["myapp/main"]
        }
    }
};

**Comment by kfranqueiro** [comment] 2015-06-04 04:57
Is it safe to assume that your `myapp/main` ultimately depends upon `dgrid/extensions/Pagination`?

I would point out that the above profile is missing `dojo` in the `packages` array which causes a long list of errors due to dependencies it can't find.  Ignoring that, if I run a build using this profile with a simple `myapp/main` that directly depends on `dgrid/extensions/Pagination`, I see the locale strings from the Pagination bundle show up in the `myapp/nls/myapp_*.js` layer bundles as expected.

**Comment by fredfortier** [comment] 2015-06-04 05:17
Yes. I am building a layer which becomes a "plug-in" to an existing
vendor framework which already loads dojo. The most reliable way that I
found to generate a clean layer free of redundant modules is to not
references the packages already in that framework (dojo, dijit, etc).
Otherwise, I would have to put every individual module in the "exclude
list" which seems excessive and error prone. The annoying downside is the
series of error messages. Feel free to let me know if you have a more
elegant solution.

I will check this again as I was actually expecting the nls file to get
cached as "url" entries in the merged layout file, not seperately under a
nls folder. This could what I am missing.

Thanks for looking into it.

On Thursday, June 4, 2015, Kenneth G. Franqueiro <notifications@github.com>
wrote:

> Is it safe to assume that your myapp/main ultimately depends upon
> dgrid/extensions/Pagination?
>
> I would point out that the above profile is missing dojo in the packages
> array which causes a long list of errors due to dependencies it can't find.
> Ignoring that, if I run a build using this profile with a simple
> myapp/main that directly depends on dgrid/extensions/Pagination, I see
> the locale strings from the Pagination bundle show up in the
> myapp/nls/myapp_*.js layer bundles as expected.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SitePen/dgrid/issues/1136#issuecomment-108721768>.
>


-- 
Frédéric Fortier

Check out my professional profile and connect with me on LinkedIn.
http://lnkd.in/aM86Kf

**Comment by kfranqueiro** [comment] 2015-06-05 02:12
nls bundles are normally kept in their own separate files, but are still consolidated based on each layer.  This is usually desirable since multiple locales are typically built, but any particular user only ever needs to load strings for one of them.

I believe it's now possible to build nls files straight into layers if you really want to, but I don't recall offhand whether it's as straightforward as just explicitly including it in the layer; I normally wouldn't recommend doing it.

**Comment by kitsonk** [comment] 2015-08-11 10:09
@kfranqueiro gave his advice and this seems to be more related to the dojo/util build system, closing in lieu of that.

**Closed by kitsonk** 2015-08-11 10:09 UTC
