### ISSUE TITLE
Tree + ColumnReorder nodes won't expand after reorder

### ISSUE THREAD

**Issue by eQuorumRayNewman** [SitePen/dgrid#1262] opened 2016-03-18 15:23 UTC
Tree nodes won't expand after columns have been reordered.  To duplicate add the ColumnReorder extension to dgrid/test/Tree.html. Run Tree.html, move the "visited" column to the leftmost column position, then attempt to expand one of the rows.

**Comment by kfranqueiro** [comment] 2016-03-18 15:27
I think this is a duplicate of #1255, which has been fixed on the master, dev-1.0, and dev-0.4 branches.  Can you try running from the latest and see if your problem is resolved?

**Comment by eQuorumRayNewman** [comment] 2016-03-18 16:12
Yep, fixed in dev-1.0.  Thanks

**Closed** 2016-03-18 16:17 UTC
