### ISSUE TITLE
OnDemandList fetches all pages before scrolling

### ISSUE THREAD

**Issue by fredfortier** [SitePen/dgrid#1026] opened 2014-10-23 01:06 UTC
I am using OnDemandList and would like to fetch pages only as I scroll.

It does fetch the data page by page using a page size of minRowsPerPage.

But it fetches all pages as I startup the list, not as I am scrolling.

One particularity of the list is that it is a thumbnail view (essentially a grid of image). So the template of each row has 'float: left;' so it can be displayed as a column as much as the horizontal space allows. I thought that the logic that you are using to assess the scroll may not like this.

Please let me know if you have any recommendations or things to look for.

**Comment by kfranqueiro** [comment] 2015-01-10 03:51
@wansj, would you be able to provide a test case that reproduces your issue?  I am not able to reproduce it using OnDemand_tile.html, even if I change it to use an async store.

**Comment by kfranqueiro** [comment] 2015-06-29 00:28
Given no further responses on this issue, I'm closing it under the assumption that the advice in https://github.com/SitePen/dgrid/issues/1026#issuecomment-60181503 resolves it.  Thanks!

**Closed by kfranqueiro** 2015-06-29 00:28 UTC
