### ISSUE TITLE
Enhancement request for Grid.set columns using the JsonRest store

### ISSUE THREAD

**Issue by lixopmstp** [SitePen/dgrid#530] opened 2013-04-05 15:35 UTC
Would it be possible to have a flag or something so that setting columns would not trigger a data request?  Here's my use case:  I have a Edit Mode button which when users click it puts editors on certain columns.  What happens is when I call set columns the grid initiates a refresh and makes a request to the backend server for data.  If the server has to run a slow query (or one that returns a lot of data) there is a noticeable delay, plus the grid data rows are blanked/deleted.  I my scenario the data does not change, just the widgets used to display/interact with it.  BTW, I do understand that in the more general case it makes sense to refresh the data and the UI.

**Comment by kfranqueiro** [comment] 2015-01-29 19:38
This sounds like a duplicate of #384, so I'm closing this one.

Accommodating this may require some refactoring in order to make dgrid reuse data that was previously obtained.

In the interim, perhaps `dstore/Cache` could help in these cases (with dgrid 0.4).

**Closed by kfranqueiro** 2015-01-29 19:38 UTC
