### ISSUE TITLE
dGrid sort parameter using dStore Rest 

### ISSUE THREAD

**Issue by bobmanc** [SitePen/dgrid#1197] opened 2015-10-24 18:56 UTC
When I fetch from a dStore the URL looks something like this

`http://localhost/rest/dojo?department=sales`

which works fine. If I then click in the header of the dGrid the sent URL looks like this.

`http://localhost/rest/dojo?department=sales&sort(+id)&limit(25)`

Shouldn't it send &sort=+id&limit=25? I am using Java and Spring for the backend and it expects the parameters to be formatted this way. Right now I can not receive the extra parameters. Is there a way to get it to send the parameters the way Spring is expecting them?

**Comment by kfranqueiro** [comment] 2015-10-24 20:53
This looks like a duplicate of [this SO question](http://stackoverflow.com/q/33310529/237950), and that's a good place for this, so I've gone ahead and answered it there.

**Closed by kfranqueiro** 2015-10-24 20:53 UTC
