### ISSUE TITLE
dGrid tree container is undefined

### ISSUE THREAD

**Issue by danielu** [SitePen/dgrid#964] opened 2014-06-23 11:27 UTC
issue better described here: 
http://stackoverflow.com/questions/24364683/dgrid-tree-container-is-undefined

**Comment by kfranqueiro** [comment] 2015-11-20 23:41
Unfortunately that SO question no longer seems to be available, so without any information left, I'm closing this.  Please feel free to open a new issue with a reproducible test case if the issue persists.

**Closed by kfranqueiro** 2015-11-20 23:41 UTC
