### ISSUE TITLE
keepScrollPosition when Tree expanded

### ISSUE THREAD

**Issue by riaeasy** [SitePen/dgrid#1268] opened 2016-04-02 05:21 UTC
Hi,
When Tree was expanded, Grid.refresh call renderQuery to keepScrollPosition, but here, the Tree not expanded yet, so keepScrollPosition is an incorrect position.

**Comment by kfranqueiro** [comment] 2016-04-04 13:47
Duplicate of #403.

**Closed by kfranqueiro** 2016-04-04 13:47 UTC
