### ISSUE TITLE
dgrid 0.4.0 tree looks flat before user interacts

### ISSUE THREAD

**Issue by mdolidon** [SitePen/dgrid#1097] opened 2015-03-05 23:28 UTC
Trying to use dgrid 0.4.0 to display a tree structure. (no prior experience with previous versions 0.3.x).

I built this sample with two folders : alice and bob ; each would have a few files (leaves) in it.

The store ("astore.js")

    define(['dojo/_base/declare',
           './dstore/Memory',
           './dstore/Tree'],

           function(declare, Memory, Tree) {
               var store = new (declare([Memory, Tree], {}))();

               store.add({node:'bob',     id:1, parent:null, hasChildren:true});
               store.add({node:'alice',   id:2, parent:null, hasChildren:true});

               store.add({node:'thesis',  id:3, parent:1,    hasChildren:false});
               store.add({node:'game',    id:4, parent:1,    hasChildren:false});
               store.add({node:'picture', id:5, parent:2,    hasChildren:false});
               store.add({node:'plan',    id:6, parent:2,    hasChildren:false});
               store.add({node:'mail',    id:7, parent:2,    hasChildren:false});

               return store;
           });

And the startup script :

    require(['dojo/_base/declare',
            'app/dgrid/OnDemandGrid',
            'app/dgrid/Tree',
            'app/astore'], 
            function (declare, OnDemandGrid, Tree, astore) {

                w = new (declare([OnDemandGrid, Tree],{}))({
                    collection: astore,
                    columns:[
                        {field:'node', label:'Whatever...', renderExpando:true}
                    ]
                }, 'slot');

                w.startup();
            });

The data always looks flat when the widget is displayed :

![enter image description here][1]

After I click on "bob", that part gets sorted out :

![enter image description here][2]

Then I click on "alice", and all looks fine at last :

![enter image description here][3]

However if I sort on a column, I mess the whole stuff up again, worse than ever :

![enter image description here][4]

I've experimented with the sample code from the laboratory, and get the same results. My dgrid components were downloaded via Bower. This issue is present on two different computers, with different OSs and browers. And I'm running dry on ideas... :S Any input extremely appreciated !

  [1]: http://kibu.fr/entrepot/dgrid_bug1/1.jpg
  [2]: http://kibu.fr/entrepot/dgrid_bug1/2.jpg
  [3]: http://kibu.fr/entrepot/dgrid_bug1/3.jpg
  [4]: http://kibu.fr/entrepot/dgrid_bug1/4.jpg

**Comment by dylans** [comment] 2015-03-05 23:54
I think the issue is that in your grid instantiation, for your collection, you need to specify a filter to just show the items that are top-level parents. For example, something like:

```javascript
collection: astore.filter({'parent': null}
```

**Comment by kfranqueiro** [comment] 2015-03-06 00:50
`dstore/Tree#getRootCollection` will basically do what Dylan is suggesting, and that's typically what you'd want to set as your grid's collection.

```js
collection: astore.getRootCollection()
```

**Comment by kfranqueiro** [comment] 2015-03-06 00:56
Given this was [cross-posted on SO](http://stackoverflow.com/q/28889591/237950) (which is where it belongs in this case), I'm closing this.  Thanks!

**Closed by kfranqueiro** 2015-03-06 00:56 UTC
