### ISSUE TITLE
Pagination links' disabled state not updated after a programmatic gotoPage

### ISSUE THREAD

**Issue by psoares** [SitePen/dgrid#1049] opened 2014-12-11 21:31 UTC
When invoking grid.gotoPage(n) programmatically, the corresponding link in the pagination widget should be disabled, giving the user feedback about which page has been selected.

I'm not observing that behavior on dgrid 0.4. I'm using it with a dstore [Rest, Cache, Trackable] store.

My grid declaration is as follows : 
```javascript
    new declare([Grid, Editor, Keyboard, Selection, Pagination])({
					collection : store.filter(tmpQ).track(),
					cellNavigation : false,
					deselectOnRefresh : false,
					allowTextSelection : true,
					keepCurrentPage : true,
					keepScrollPosition : true,
			                rowsPerPage : 25,
					columns : [...],
					selectionMode : 'single'
    });
```

**Comment by kfranqueiro** [comment] 2015-10-16 22:21
I am unable to reproduce this on the Pagination test pages (e.g. http://dgrid.io/js/dgrid/test/extensions/Pagination.html).

Ultimately, the code that handles clicks in the UI simply calls `gotoPage` as well, so I'd expect this to either work or break consistently both through the UI or programmatically.

If you are still experiencing this issue, would you be able to share a gist of a full reproducible test case?

**Comment by kfranqueiro** [comment] 2015-11-20 23:08
Given no further response, and our inability to reproduce the problem, I'm closing this issue.  If you still experience the problem and can provide a standalone test case reproducing it, we'll happily take another look.  Thanks!

**Closed by kfranqueiro** 2015-11-20 23:08 UTC
