### ISSUE TITLE
dgrid column renderCell doesn't show any error or debug message in firebug

### ISSUE THREAD

**Issue by lyz19890927** [SitePen/dgrid#990] opened 2014-08-18 02:57 UTC
dgrid column renderCell doesn't show any error or debug message in firebug,there must be some problem happened,because the script stopped there and not go on anymore.This is very annoyed because it's just silent,I can't see any message.
I was wonder if there are some config which can open the log.

**Comment by kfranqueiro** [comment] 2015-11-20 23:47
Given that no code was provided to reproduce the issue, it's impossible to guess at the cause.  You're right that ordinarily if an error occurs during `renderCell` that it would cause any browser's developer tools to pause if break on error is enabled.

I'm closing this, but if you continue to experience this, please provide a reproducible test case so we can hopefully get to the bottom of it.

**Closed by kfranqueiro** 2015-11-20 23:47 UTC
